---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-tv-pv
spec:
  storageClassName: media-tv
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: /mnt/user/tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-tv-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-tv
  resources:
    requests:
      storage: 1Mi


