---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-movies-pv
spec:
  storageClassName: media-movies
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: /mnt/user/movies
  mountOptions:
  - nfsvers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-movies-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: media-movies
  resources:
    requests:
      storage: 1Mi