---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-movies-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    name:  nfs-media-movies-pvc
    namespace: media
  storageClassName: nfs
  nfs:
    server: ${NFS_SERVER_IP}
    path: /mnt/user/movies/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-movies-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi