---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: nzbget
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/nzbget
      tag: v21.1
    env:
      TZ: "America/New_York"
    ingress:
      enabled: true
      hosts:
      - host: "nzbget.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "nzbget.${SECRET_DOMAIN}"
      additionalIngresses:
      - enabled: true
        nameSuffix: "api"
        hosts:
        - host: "nzbget.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "nzbget.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: nzbget-config-v1
    additionalVolumeMounts:
    - name: media-downloads
      mountPath: "/downloads"
    additionalVolumes:
    - name: media-downloads
      persistentVolumeClaim:
        claimName: nfs-media-downloads-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 7500Mi