---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.14
    env:
      TZ: "America/New_York"
    replicas: 3
    service:
      port:
        port: 4000
      additionalServices:
      - enabled: true
        nameSuffix: dns
        type: LoadBalancer
        loadBalancerIP: "${LB_BLOCKY_IP}"
        port:
          port: 53
          name: dns-udp
          protocol: UDP
          targetPort: 53
        externalTrafficPolicy: Local
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    prometheus:
      serviceMonitor:
        enabled: true

    config: |
      upstream:
        # these external DNS resolvers will be used. Blocky picks 2 random resolvers from the list for each query
        # format for resolver: net:host:[port][/path]. net could be tcp, udp, tcp-tls or https (DoH). If port is empty, default port will be used (53 for udp and tcp, 853 for tcp-tls, 443 for https (Doh))
        externalResolvers:
        - udp:1.1.1.1
        - udp:8.8.8.8
      customDNS:
        mapping:
          localhost: 127.0.0.1
          ${SECRET_DOMAIN}: ${INGRESS_NGINX_LB}
      blocking:
        blackLists:
          ads:
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          special: []
          #   - https://hosts-file.net/ad_servers.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
            # - special
      httpPort: 4000
      logLevel: info
      prometheus:
        # enabled if true
        enable: true
        # url path, optional (default '/metrics')
        path: /metrics