---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: home
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: goldilocks
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.fairwinds.com/stable
    name: goldilocks
    version: 3.0.3
  values:
    installVPA: true
    dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: goldilocks.${SECRET_DOMAIN}
            paths: ["/"]
        tls:
          - hosts:
              - goldilocks.${SECRET_DOMAIN}
    resources:
      limits:
        cpu: 25m
        memory: 250Mi
      requests:
        cpu: 25m
        memory: 250Mi