---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: object-store
  namespace: system-rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 2
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  preservePoolsOnDelete: true
  gateway:
    type: S3
    sslCertificateRef:
    port: 80
    # securePort: 443
    instances: 2
  healthCheck:
    bucket:
      disabled: false
      interval: 60s