---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-adguard-home
  namespace: networking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
