---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.105.2
      pullPolicy: Always
    persistence:
      config:
        enabled: true
      data:
        enabled: true
        existingClaim: database-adguard-home
    env:
      TZ: "America/New_York"
      PUID: "1000"
      PGID: "1000"
    service:
      port:
        port: 3000
      additionalServices:
      - enabled: true
        nameSuffix: dns-tcp
        type: LoadBalancer
        # loadBalancerIP: "${LB_ADGUARD_IP}"
        externalIPs:
        - 10.0.0.90
        port:
          port: 53
          name: dns-tcp
          protocol: TCP
          targetPort: 53
        externalTrafficPolicy: Local
      - enabled: true
        nameSuffix: dns-udp
        type: LoadBalancer
        # externalIPs:
        # - "${CLUSTER_LB_ADGUARD_HOME}"
        externalIPs:
        - 10.0.0.90
        port:
          port: 53
          name: dns-udp
          protocol: UDP
          targetPort: 53
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "adguard.${SECRET_DOMAIN}"  
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "adguard.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
      limits:
        memory: 2000Mi