# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:8y8X+Ztl7c7TA5qtrBEa0sVpIKxb+B/1/93eAaN0dZjB6ZUB84kMRA==,iv:bb8BBsf/eR6c6HVXpNtjeK4DByU2QXKIcw6fBcvi8w4=,tag:1ucQmH0Us8aT6MmFblVtmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-14T13:56:58Z"
    mac: ENC[AES256_GCM,data:2bp/MPY9Ix1BPZ0pwEyy01hI9DfPRx0Gv7IXTPhlu89EMWoK797zaRrMn2qqUIXz1+mfBkG+qr23qeV3S3mtFpENSjMaVEJ/hhwPN/wB6UUAJmIRDDtRnxbW+55kL+V3N9ys+hBoulKglQ9dZZnaAxa25NrwsFiH57eCI1uD1IM=,iv:bBoqyOw5rS6ldBuwPnKLeJVGE90+BKAm+jqDD+TL4d4=,tag:LR3ixf5as7d7JjNqiiWuWg==,type:str]
    pgp:
        - created_at: "2021-05-14T13:56:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3EaUJvXHX2GAQ/7BWfG1B+0CuVV9SXUd//2uxoRU673ZQMvh2EAU3+L3vOQ
            wQiqoalyqvZ/srantaJ8ac9fmpXUhUgy7LaHQqwKWQUMtjB0QpvC7X2Zky6Z2UIy
            7MhXp+NL+d1NwLLqMv7uhmfQQSzKOgd1DxZITjNSQcugEblIXOU4v/8mEWJwFWmN
            5IvZhjqn6a94yS6Lkx77qztQEV/Kh7mpteQ8x6hRx4iWslaI1LQXNPiIGHujYEse
            PZvEpf3+Ffui0ZJlP4OAqVQ4MXZNWuzATK0AdtwA0g60Xo+mJaJGzUp9cJu9grMp
            aWboT2y5G7jLIK+ONhaQhX7hO9+dm6dXH9xet98Ap6qHVLyUlZEbpbik75CF3efE
            yYUOXxW7ZqkxSjo9HXXlI6EObkRvrUcIwjjoUkKDgIO9qNPZ7zYHn0vyQzWqGhqN
            RdDjQb9qvOvTAuZ+yUflj0vercC5NrUJ6oUtfCmSczAQaraveOHXeoW0U0c4guXv
            wao4oEOQiXfph1n/l7YhegC7CsEqFTLZlmSA9vfa6en5dmv6Iv9h4hSV8xyMe062
            KU5VE44WGJRN6v/bqxJ/O7QgunciBMNUj2e370LfiI8jHNMT+wrDTTRs8Igi/cS1
            M17OExXxmXA++ZKt6Orxp7BjgAr7nY5iyA6hKqvUw9/4J0+cY3x7KjP1WyivAlTS
            XgH4UvxfDsWfmOC7Wa2Sp3WtJD2Ku4ZAPXedkS+jggxGTfArQsn4m8X9PcWb6AUy
            O6/YAs/tbpDTz5EEVMSjFHG/eeawYYVK65MScwOt7HPXBs2Dzf1WwILApWSFi5M=
            =35Nh
            -----END PGP MESSAGE-----
          fp: FC834F17FF1DE2A031029D5AF41FD3CE2D21DCEB
        - created_at: "2021-05-14T13:56:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzuJ1VYnoUIPAQ/9GUlhEnM3ugEiMo9Ytqk1OVhS+ia3G8LmMu0WtZQCxtOi
            Mm0Tx8qadC/fev6ULob1d92nrWdpCKRSsjetOEn7bWegzOSUkpMmanrUaVegKJfX
            hTniadSP+OOOjDEv7pkW5IbMdfqYvzOnSP5hHb9kQ89ID/uh/6zcocNEiE58vrTm
            R6sOvWyISlRKRmnt7q+c9oEbjaouQ8XimMBbgNVgP+MdqAvoUEEBFm3ePjuDQ//3
            Mz+wudvlP+MYfFsTfFbIEg/4//ztq+QYuAFPu9tV1z1kGIO+KbfWDoTe39kvpXKC
            Vh2m/7zRXZ3RqpNsNuQb+y+OlUSEmg4qfWbWVmOuXWs6KyrCXdaX6ixNMBNF6yeA
            xy9cNxCXUr36bvUdNckM569uvfiSjhW13C47ynz46g7tkPyPNe0aWzAX7yycEUTO
            jWBhSAyMkDlSihkNFPek8+tthn6FkkWviLtBMwXF1zoEQI5YrN6myUeo0eLwK3zD
            XHwoi5973HzWQZY20sfhnmbVNjcG/dbxBmzoWB7HRCbQSQKwhFx+puhH0b/z7odQ
            DRSBSqMSWxYETfHv/CMOP5oZxjG8Ko/nub3Sjf58Ll8K/7xwcDV2eZtpu2rK+p0Y
            k2SZOI7V2xSWl0PzfFc/ZsZyCaoauCgDL6Bw4oQOfbmuz8Wo6i2jzKq0E8mrYzPS
            XgE+a8Hh7HpKGO4YeT2iL1K+ZeAzj3FIwYmDEpyMCw3+fSXLDNsBMbHajecoXzyD
            FsSYB1nsFhVx/RMvRRBlBgp123CHPkt7vHa9XincjEFv/pG4afpew2U8Pja/mV4=
            =eVSZ
            -----END PGP MESSAGE-----
          fp: B737F07A436019CC00C137EECA4332FCF09BC4B0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
